IMDB/Models/Film.cs
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace IMDB.Models
{
    public class Film
    {
        [Key]
        public int Id { get; set; }

        [Required]
        [MinLength(1)]
        public string Name { get; set; }

        [Required]
        [MinLength(1)]
        public string Genre { get; set; }

        [Required]
        [MinLength(1)]
        public string Director { get; set; }

        [Range(1900, 2100)]
        public int Year { get; set; }
    }
}

IMDB/Models/IMDBDbContext.cs
using System.Data.Entity;

namespace IMDB.Models
{
    public class IMDBDbContext : DbContext
    {
        public virtual IDbSet<Film> Films { get; set; }

        public IMDBDbContext() : base("IMDB")
        {
        }
    }
}

IMDB/Controllers/FilmController.cs
using System.Linq;
using System.Net;
using System.Web.Mvc;
using IMDB.Models;

namespace IMDB.Controllers
{
    [ValidateInput(false)]
    public class FilmController : Controller
    {
        private IMDBDbContext db = new IMDBDbContext();

        [HttpGet]
        [Route("")]
        public ActionResult Index()
        {
            var films = db.Films.ToList();
            return View(films);
        }

        [HttpGet]
        [Route("create")]
        public ActionResult Create()
        {
            return View(new Film());
        }

        [HttpPost]
        [Route("create")]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Film film)
        {
            if (this.ModelState.IsValid)
            {
                db.Films.Add(film);
                db.SaveChanges();
                return Redirect("/");
            }

            return View(film);
        }

        [HttpGet]
        [Route("edit/{id}")]
        public ActionResult Edit(int? id)
        {
            var film = db.Films.Find(id);
            if (film == null)
                return HttpNotFound();

            return View(film);
        }

        [HttpPost]
        [Route("edit/{id}")]
        [ValidateAntiForgeryToken]
        public ActionResult EditConfirm(int? id, Film filmModel)
        {
            var filmFromDb = db.Films.Find(id);
            if (filmFromDb == null)
                return HttpNotFound();

            if (this.ModelState.IsValid)
            {
                filmFromDb.Name = filmModel.Name;
                filmFromDb.Genre = filmModel.Genre;
                filmFromDb.Director = filmModel.Director;
                filmFromDb.Year = filmModel.Year;

                db.SaveChanges();

                return Redirect("/");
            }

            return View("Edit", filmModel);
        }

        [HttpGet]
        [Route("delete/{id}")]
        public ActionResult Delete(int? id)
        {
            var film = db.Films.Find(id);
            if (film == null)
                return HttpNotFound();

            return View(film);
        }

        [HttpPost]
        [Route("delete/{id}")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirm(int? id)
        {
            var filmFromDb = db.Films.Find(id);
            if (filmFromDb == null)
                return HttpNotFound();

            db.Films.Remove(filmFromDb);
            db.SaveChanges();

            return Redirect("/");
        }
    }
}

IMDB/Views/Film/Create.cshtml
@model IMDB.Models.Film

@{
    ViewBag.Title = "Create Film";
}

<h1>Create Film</h1>

<section>
    <div>
        @using (Html.BeginForm("Create", "Film", FormMethod.Post))
        {
            @Html.AntiForgeryToken()

            @Html.ValidationSummary()

            <label for="name">Name</label>
            <input type="text" id="name" name="name"
                   value="@Model.Name">
            @Html.ValidationMessageFor(m => m.Name)

            <label for="genre">Genre</label>
            <input type="text" id="genre" name="genre"
                   value="@Model.Genre">
            @Html.ValidationMessageFor(m => m.Genre)

            <label for="director">Director</label>
            <input type="text" id="director" name="director" value="@Model.Director">
            @Html.ValidationMessageFor(m => m.Director)

            <label for="year">Year</label>
            <input type="text" id="year" name="year"
                   value="@Model.Year">
            @Html.ValidationMessageFor(m => m.Year)

            <button type="submit" class="">Create</button>
            <button onclick="location.href='/';return false;" class="cancel">Cancel</button>
        }
    </div>
</section>

IMDB/Views/Film/Delete.cshtml
@model IMDB.Models.Film

@{
    ViewBag.Title = "Delete Film";
}

<h1>Delete Film</h1>

<section>
    <div>

        @using (Html.BeginForm("Delete", "Film", FormMethod.Post))
        {
            @Html.AntiForgeryToken()

            <label for="name">Name</label>
            <input type="text" id="name" value="@Model.Name" disabled>
            <label for="genre">Genre</label>
            <input type="text" id="genre" value="@Model.Genre" disabled>
            <label for="director">Director</label>
            <input type="text" id="director" value="@Model.Director" disabled>
            <label for="year">Year</label>
            <input type="text" id="year" value="@Model.Year" disabled>

            <button type="submit" class="accept">Delete</button>
            <button onclick="location.href='/';return false;" class="cancel">Cancel</button>
        }

    </div>
</section>

IMDB/Views/Film/Edit.cshtml
@model IMDB.Models.Film

@{
    ViewBag.Title = "Edit Film";
}

<h1>Edit Film</h1>

<section>
    <div>

        @using (Html.BeginForm("Edit", "Film", FormMethod.Post))
        {
            @Html.AntiForgeryToken()

            @Html.ValidationSummary()

            <label for="name">Name</label>
            <input type="text" id="name" value="@Model.Name" name="name">
            @Html.ValidationMessageFor(m => m.Name)

            <label for="genre">Genre</label>
            <input type="text" id="genre" value="@Model.Genre" name="genre">
            @Html.ValidationMessageFor(m => m.Genre)

            <label for="director">Director</label>
            <input type="text" id="director" value="@Model.Director" name="director">
            @Html.ValidationMessageFor(m => m.Director)

            <label for="year">Year</label>
            <input type="text" id="year" value="@Model.Year" name="year">
            @Html.ValidationMessageFor(m => m.Year)

            <button type="submit" class="accept">Edit</button>
            <button onclick="location.href='/';return false;" class="cancel">Cancel</button>
        }

    </div>
</section>

IMDB/Views/Film/Index.cshtml
@model List<IMDB.Models.Film>

@{
    ViewBag.Title = "All Films";
}

<h1>All Films</h1>

<div>
    <button onclick="location.href='/create';return false;" class="add-new">Create New Film</button>
</div>

<section>
    <div>
        <table>
            <tr>
                <th>Name</th>
                <th>Genre</th>
                <th>Director</th>
                <th>Year</th>
                <th>Actions</th>
            </tr>
            @foreach (var film in Model)
            {
                <tr>
                    <td>@film.Name</td>
                    <td>@film.Genre</td>
                    <td>@film.Director</td>
                    <td>@film.Year</td>
                    <td>
                        <button onclick="location.href='/edit/@film.Id';return false;" class="edit">Edit</button>
                        <button onclick="location.href='/delete/@film.Id';return false;" class="delete">Delete</button>
                    </td>
                </tr>
            }
        </table>
    </div>
</section>

IMDB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
	<title>IMDB</title>
	@Styles.Render("~/Content/style.css")
</head>
<body>
	@RenderBody()
</body>
</html>